/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215711;

public class App {
    static String str = "百二十三";
    public int DoingParseInt(String strings){
        int num = Integer.parseInt(strings);
        return num;
    }
    public static void main(String[] atgs){
        App parse = new App();
        System.out.println(parse.DoingParseInt(str));
    }
}
