/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215711;

public class App {
    String str = null;
    public void howLength(){
        System.out.println(str.length());
    }
    public static void main(String[] args) {
        App how  = new App();
        how.howLength();
    }
}
